#!/usr/bin/python
# $Id: $
import sys, os

path = os.getenv('PATH').split(os.pathsep)

pathlist = []
for i in range(len(path)):
    pathlist.append("    %s: %s" % (i, path[i]))

pathstr = "\n".join(pathlist)

if '/usr/local/bin' in path:
    target = "/usr/local/bin"
elif '/usr/bin' in path:
    target = "/usr/bin"
elif path:
    target = path[0]
else:
    print """
    Error: The environmental variable 'PATH' is not defined. Contact your
    system administrator.
    """
    sys.exit(0)

# begin dependency checks
FAIL = 0
d = os.getcwd()
v = sys.version.split()[0]
if v < '2.3':
    print "Error: You have version %s of Python installed. You need Python >= 2.3 to use this package."\
            % v
    FAIL = 1
try:
    import wx
    w = wx.VERSION_STRING
    if w < '2.6.1':
        print "Error: You have version %s of wxPython installed. You need wxPython >= 2.6.1 to use this package." % w
        FAIL = 1
except:
    print "Error: You do not have wxPython installed. You need wxPython >= 2.6.1 to use this package."
    FAIL = 1

if FAIL:
    sys.exit(0)
# end dependency checks

# create the symbolic links

print """
                   ===============================
                        wxRemind Installation
                   ===============================

You have python %s and wxPython %s installed and thus satisfy the
dependency requirements for wxRemind.

All that remains to complete the installation is to create symbolic links from
the python scripts wxremind, wxremalert and wxremdata to a directory in your
executable path:

%s

Please choose the number of the directory you would like to use or enter an
empty response to use %s.
""" % (v,w,pathstr,target)

response = raw_input("Number of directory to use for links? ")

if response:
    dstnum = int(response)
    if dstnum in range(len(path)):
        target = path[int(dstnum)]
    else:
        print """
        Error: %d is not the number of one of the listed alternatives. Please
        start over and select the number of one of the listed alternatives.
        """ % dstnum
        sys.exit(0)

print """
Creating symbolic links in %s ...
""" % target

if not os.access(target, os.F_OK):
    print """
    Error: %s does not exist. Either create this directory or use an existing
    directory in your path when you start over.
    """ % target
    sys.exit(0)

if not os.access(target, os.R_OK | os.W_OK | os.X_OK):
    print """
    Error: You do not have permission to create links in %s. 
    Please start over with a directory in which you can create
    symbolic links.
    """ % target
    sys.exit(0)


try:
    for file in ['wxremalert', 'wxremdata', 'wxremind']:
        src = "%s/%s" % (d, file)
        dst = "%s/%s" % (target, file)
        try:
            os.remove(dst)
            print "Removed existing link %s" % dst 
        except:
            pass
        os.symlink(src, dst)
        if os.access(dst,os.X_OK):
            print "Created symbolic link %s" % dst
        else:
            print """
            Error: %s is not executable.
            """ % dst
            raise OSError
except:
    print "Failed to create the necessary symbolic links in %s" % target
    sys.exit(0)




print """ 
                   ===============================
                        Successful Completion
                   ===============================

You can now run wxRemind by opening a terminal window and entering

> wxremind

Once wxRemind is running, pressing ? will bring up a display of usage
information. 

To enable floating reminders don't forget to insert the line

    INCLUDE %s/FLOAT 

in your reminders file prior to your first floating reminder - after adjusting

    %s

to reflect the new location if you move FLOAT. 

Last but not least, move WXREMINDRC to ~/.wxremindrc and edit it to reflect
your own preferences.  Note in particular that the default editor is
/usr/local/bin/gvim and the default reminders file is ~/.reminders.
""" % (d,d)
