#!/usr/bin/python
import sys, datetime
from wxRemind.wxRemData import RemData

if len(sys.argv) == 4:
    y,m,d = sys.argv[1:4]
else:
    today = datetime.date.today()
    y, m, d = today.strftime("%Y %m %d").split()
mydata = RemData()
y,m,d = map(int, (y,m,d))
fmt = "%%a %s %%b %%Y" % d
print "%s:" % datetime.date(y,m,d).strftime(fmt)
for event in mydata.getDay(y,m,d):
    if not event[1]:
        event[1] = ' '
    str = "%7s %s %7s %s" % (event[0], event[1], event[2], event[3])
    print "  %s" % str
