#!/usr/bin/python
# $Id: $
import sys, os

# begin dependency checks
FAIL = 0
d = os.getcwd()
v = sys.version.split()[0]
if v < '2.3':
    print "Error: You have version %s of Python installed. You need Python >= 2.3 to use this package."\
            % v
    FAIL = 1
try:
    import wx
    w = wx.VERSION_STRING
    if w < '2.6.1':
        print "Error: You have version %s of wxPython installed. You need wxPython >= 2.6.1 to use this package." % w
        FAIL = 1
except:
    print "Error: You do not have wxPython installed. You need wxPython >= 2.6.1 to use this package."
    FAIL = 1

if FAIL:
    sys.exit(0)
# end dependency checks

from pkg_resources import Requirement, resource_filename
wxremindrc = resource_filename(Requirement.parse("wxRemind"),"WXREMINDRC") 
float = resource_filename(Requirement.parse("wxRemind"),"FLOAT") 

print """\
                   ===============================
                        Successful Completion
                   ===============================

wxRemind has been installed and your versions of 

    python: %s 

and 

    wxPython: %s

have been verified as satisfying the dependency requirements.
""" % (v,w)

print """\

Temporary copies of the files 'FLOAT' and 'WXREMINDRC' have been installed at
the following locations:

FLOAT:      %s

WXREMINDRC: %s

Copy FLOAT to a convenient location and then insert the following line
somewhere near the beginning of your reminders file (typically ~/.reminders)
after replacing <Path to FLOAT> with the correct location:

    INCLUDE <Path to FLOAT>/FLOAT

Finally, edit WXREMINDRC to suit your own preferences and then save the
resulting file as ~/.wxremindrc. Pay particular attention to the settings for
editor (initially /usr/local/bin/gvim) and reminders (initially ~/.reminders).
Both of these settings must be correct for your location.

You can now run wxRemind by opening a terminal window and entering at the
command prompt:

$ wxremind

Once wxRemind is running, pressing ? will bring up a display of usage
information.\
""" % (float, wxremindrc)

